workspace(name = "test_legacy")

local_repository(
    name = "rules_tensorrt",
    path = "../../",
)

load("@rules_tensorrt//:repo.bzl", "config_tensorrt")

config_tensorrt(
    name = "tensorrt",
    required = False,
)

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

# Jan 4th 2026
rules_cuda_revision = "bfea6eea03ea6acd174ab21ba6309d08d358d0d7"

http_archive(
    name = "rules_cuda",
    integrity = "sha256-Zdphe+6WvAvQgllPus6j5S+cG1qGHtEbp+3ZzirleHw=",
    strip_prefix = "rules_cuda-%s" % rules_cuda_revision,
    urls = ["https://github.com/bazel-contrib/rules_cuda/archive/%s.tar.gz" % rules_cuda_revision],
)

load("@rules_cuda//cuda:repositories.bzl", "rules_cuda_dependencies", "rules_cuda_toolchains")

rules_cuda_dependencies()

rules_cuda_toolchains(register_toolchains = True)
