workspace(name = "test_legacy")

local_repository(
    name = "rules_tensorrt",
    path = "../../",
)

load("@rules_tensorrt//:repo.bzl", "config_tensorrt")

config_tensorrt(
    name = "tensorrt",
    required = False,
)

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

# https://github.com/bazel-contrib/bazel_features
bazel_features_version = "1.36.0"

http_archive(
    name = "bazel_features",
    integrity = "sha256-k5CzkaaNOySu95ZrzoVW0oAD/j8CKlAI78eAforKrxo=",
    strip_prefix = "bazel_features-%s" % bazel_features_version,
    url = "https://github.com/bazel-contrib/bazel_features/archive/refs/tags/v%s.tar.gz" % bazel_features_version,
)

rules_cc_version = "0.0.14"

http_archive(
    name = "rules_cc",
    integrity = "sha256-kG6JKGrMZ8IIGcPIizKD3g1YaK/aM2NdcKyuDel3e7c=",
    strip_prefix = "rules_cc-%s" % rules_cc_version,
    url = "https://github.com/bazelbuild/rules_cc/archive/refs/tags/%s.tar.gz" % rules_cc_version,
)

# Jan 4th 2026
rules_cuda_revision = "bfea6eea03ea6acd174ab21ba6309d08d358d0d7"

http_archive(
    name = "rules_cuda",
    integrity = "sha256-Zdphe+6WvAvQgllPus6j5S+cG1qGHtEbp+3ZzirleHw=",
    strip_prefix = "rules_cuda-%s" % rules_cuda_revision,
    urls = ["https://github.com/bazel-contrib/rules_cuda/archive/%s.tar.gz" % rules_cuda_revision],
)

load("@rules_cuda//cuda:repositories.bzl", "rules_cuda_dependencies", "rules_cuda_toolchains")

rules_cuda_dependencies()

rules_cuda_toolchains(register_toolchains = True)
